name: 'Telegram Notification'
description: 'Send deployment status notifications to Telegram'
inputs:
  token:
    description: 'Telegram bot token'
    required: true
  chatId:
    description: 'Telegram chat id'
    required: true
  status:
    description: 'Deployment status (success or failure)'
    required: false
  githubDataBase64:
    description: 'Base64 encoded GitHub event data'
    required: false
  errorMessage:
    description: 'Error message in case of failure'
    required: false
    default: ''
runs:
  using: 'node20'
  main: 'dist/index.js'
